### ISSUE TITLE
Incoming creatures sometimes go to containment chamber despite settings

### ISSUE THREAD

**Issue by Xerus2** [AlbianWarp/AlbianWarpServer#48] opened 2020-04-20 16:59 UTC
I have my containment chamber configured with no one in either the "send to" or "receive from" lists, and I have two separate portals created, one for incoming creatures set to receive from "any on-line user" and out for outgoing creatures set to send to "any on-line user". With this setup, I would expect that any incoming creatures would go to my configured portal, and never go to the containment chamber, but it seems that creatures occasionally pop into the chamber regardless. I am not sure if this is a change of behavior from the original warp, but I think being able to disable the containment chamber from receiving would be a good thing to have, if it's possible to implement. I've seen this issue with both the old Albian Warp client and the new Rebabel implementation.

**Comment by KeyboardInterrupt** [comment] 2021-12-21 17:38
I was unable to reproduce this, I will close this issue.
Have you encountered this issue more than once?
And can you now still reproduce it?
If you either cant reproduce it, or don't have the Game installed, no worries, I am sure it will come up again, if this happens again.
If you can reproduce this issue, please feel free to comment on this issue, and I will open it again right away!

Thank you for taking the time to file in an Issue! :heart:

**Closed by KeyboardInterrupt** 2021-12-21 17:38 UTC
